### ISSUE TITLE
arcadeDrive() logic appears to be incorrect

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/RobotCode2019#19]
Was arcadeDrive() tested on the elex board to ensure that it produces valid results for all 4 cases?

It looks broken to me. For example, if speed = 0 and rot = -1, it would appear to produce left=-1 and right=-1. There are probably other cases that are wrong as well.

It also seems to to assume that leftJoy.getY() will return a value > 0 when the operator is has the joystick pushed forward, but I don't think that's the case.

**Comment by brettle** [comment]
Also the joystick squaring calculations are wrong.

They also aren't squaring the joystick values, they are squaring the motor values which may or may not produce the desired behavior.

**Comment by kevinzwang** [comment]
Oh the joystick squaring stuff, the code was initially squaring the motors and I changed them to square the joysticks but then i probably forgot to delete the motor squaring code

**Comment by kevinzwang** [comment]
The arcade drive code is copied directly from wpilib's arcade drive so I'm not sure but I'll check once again

**Comment by brettle** [comment]
After another look, the arcade drive if statements do ahead to be correct (sorry for the false alarm) but you are incorrectly squaring and (I think) making an incorrect assumption about what getY() returns when the joystick is pushed forward.

**Comment by brettle** [comment]
Fixed in PR #20.
