### ISSUE TITLE
Acceleration term is omitted from Characterized Drive

### ISSUE THREAD

**Issue by alexander-mcdowell** [DeepBlueRobotics/RobotCode2019#36]
This is not really an issue, just a reminder. In the future, we may want to include this term in order to have maximal performance. To include the term, just set the acceleration value in characterization drive to the desired acceleration (currently it is 0.0).

FYI this is in the drivetrain-characterization branch.

**Comment by doawelul** [comment]
After a discussion with drivers, we decided that we want the acceleration to be such that the robot stays on 4 wheels (does not tip onto 2 wheels).

**Comment by alexander-mcdowell** [comment]
This has been fixed by the most recent commit (3b543c7)
