### ISSUE TITLE
Encoder rates may not work on the competition robot

### ISSUE THREAD

**Issue by alexander-mcdowell** [DeepBlueRobotics/RobotCode2019#75]
This is beyond our control, but Dean and I theorized that the drivetrain encoder rates that are being put to SmartDashboard are zero. This is because a SingularMatrixException is raised when Drivetrain Characterization Analysis is run, implying that there is only a singular value in the input matrix. Further testing will be done to confirm that this is the case.

**Comment by brettle** [comment]
Lex, see me at the next worksession. We'll take a look at the comp bot and see if we can track down the problem.

**Comment by brettle** [comment]
Since I won't be at a worksession until Sunday, please work with @kevinzwang and/or someone from senact to look at the comp bot (through the bag) to see if you can identify the problem.

**Comment by kevinzwang** [comment]
Most likely an electrical issue instead of programming. See [Gia's mattermost message](https://chat.carlmontrobotics.org/team-199/pl/hhmsrk7g1ff1zfbuwieg7nf7fa)
