### ISSUE TITLE
Drivetrain throws exceptions that crash the code

### ISSUE THREAD

**Issue by SaltyJoke** [DeepBlueRobotics/RobotCode2019#88]

**Comment by alexander-mcdowell** [comment]
Before resolving this issue, delete pull request issue-63. That was a git mistake I made

**Comment by SaltyJoke** [comment]
Is "Push issue-63 (actually issue-88)" supposed to be deleted or merged?

**Comment by brettle** [comment]
This was fixed by PR #89.
