### ISSUE TITLE
setFPS on Camera Server object does not work

### ISSUE THREAD

**Issue by alexander-mcdowell** [DeepBlueRobotics/RobotCode2019#9]
This is on the drivetrain branch in Robot.java. Perhaps CameraServer.getInstance().startAutomaticCapture() should be separate from .setFPS()?

**Comment by brettle** [comment]
It doesn't appear to be possible to set FPS on the LifeCam's, but we don't need to. We decided to just switch between the 2 feeds to save bandwidth.
